import { KeyboardKeys } from '../models/keyboard';

export const KEYS_ARRAY = [
  "Q",
  "W",
  "E",
  "R",
  "T",
  "Y",
  "U",
  "I",
  "O",
  "P",
  "A",
  "S",
  "D",
  "F",
  "G",
  "H",
  "J",
  "K",
  "L",
  "ENTER",
  "Z",
  "X",
  "C",
  "V",
  "B",
  "N",
  "M",
  "BACKSPACE",
];

export const KEYS: KeyboardKeys = [
  [
    { label: "Q", value: "Q" },
    { label: "W", value: "W" },
    { label: "E", value: "E" },
    { label: "R", value: "R" },
    { label: "T", value: "T" },
    { label: "Y", value: "Y" },
    { label: "U", value: "U" },
    { label: "I", value: "I" },
    { label: "O", value: "O" },
    { label: "P", value: "P" },
  ],
  [
    { label: "A", value: "A" },
    { label: "S", value: "S" },
    { label: "D", value: "D" },
    { label: "F", value: "F" },
    { label: "G", value: "G" },
    { label: "H", value: "H" },
    { label: "J", value: "J" },
    { label: "K", value: "K" },
    { label: "L", value: "L" },
  ],
  [
    { label: "SEND", value: "ENTER" },
    { label: "Z", value: "Z" },
    { label: "X", value: "X" },
    { label: "C", value: "C" },
    { label: "V", value: "V" },
    { label: "B", value: "B" },
    { label: "N", value: "N" },
    { label: "M", value: "M" },
    { label: "BACK", value: "BACKSPACE" },
  ],
];
